import reactConfig from "@deluxeowl/lint/react"
import {
    defineConfig,
} from "eslint/config"

export default defineConfig([
    {
        // Generated by unplugin-auto-import; committed so CI type-aware lint
        // and typecheck can resolve the auto-imported globals without running Vite.
        ignores: ["auto-imports.d.ts"],
    },
    {
        extends:  [reactConfig(import.meta.dirname)],
        settings: {
            "better-tailwindcss": {
                entryPoint: "src/index.css",
            },
        },
    },
])
